# lots of ideas from here: https://github.com/dflook/terraform-github-actions
---
name: "reusable-helm-build"

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      helm_package_name:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_account:
        required: true
      aws_assume_role:
        required: true
      aws_secret_access_key:
        required: true

env:
  # cluster vars
  AWS_REGION: ${{ inputs.aws_region }}

jobs:
  reusable-helm-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      # https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --chart-dirs helm)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: helm chart build
        if: ${{ (github.event_name == 'push') && (github.event_name != 'pull_request') }}
        run: |
          helm package helm/chart

      - name: Configure AWS Credentials
        id: aws-sts
        uses: aws-actions/configure-aws-credentials@v1
        if: ${{ (github.event_name == 'push') && (github.event_name != 'pull_request') }}
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600
          role-skip-session-tagging: true
          role-to-assume: arn:aws:iam::${{ secrets.aws_account }}:role/${{ secrets.aws_assume_role }}

      - name: aws ecr logging
        if: ${{ (github.event_name == 'push') && (github.event_name != 'pull_request') }}
        run: |
          aws ecr get-login-password \
          --region ${{ env.AWS_REGION }} | helm registry login \
          --username AWS \
          --password-stdin ${{ secrets.aws_account }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: push helm chart to ecr
        if: ${{ (github.event_name == 'push') && (github.event_name != 'pull_request') }}
        run: |
          charts=$(ls *.tgz | xargs)
          helm push ${charts} oci://${{ secrets.aws_account }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/helm/
