name: reusable-db-migration
on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      repository_name:
        required: true
        type: string
      namespace:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      pipeline_env:
        required: true
        type: string
      pipeline_tenant:
        required: true
        type: string
      pipeline_zone:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_account:
        required: true
      aws_assume_role:
        required: true
      submodule_gh_secret:
        required: false

env:
  SUBMODULE_GH_SECRET: ${{ secrets.submodule_gh_secret }}

jobs:
  db-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ env.SUBMODULE_GH_SECRET == '' }}
        uses: actions/checkout@v2
        with:
          path: ./
          
      - name: Checkout with submodules
        if: ${{ env.SUBMODULE_GH_SECRET != '' }}
        uses: actions/checkout@v2
        with:
          path: ./
          token: ${{ env.SUBMODULE_GH_SECRET }}
          submodules: recursive

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.23.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Setup binaries(aws-cli/kustomize/iam-authenticator)
        uses: bitbuy-infrastructure/bb-cicd/.github/actions/setup-aws-kustomize@main
        with:
          cluster-authentication-role-arn: ${{ secrets.aws_assume_role }}
          cluster-name: ${{ inputs.cluster_name }}
          region: ${{ inputs.aws_region }}

      - name: Check Namespace
        run: |
          NAMESPACE=${{ inputs.namespace }}
          kubectl create namespace $NAMESPACE || echo "Namespace already exists"
      
      - name: Database migration
        if: ${{ env.SUBMODULE_GH_SECRET == '' }}
        uses: bitbuy-infrastructure/bb-cicd/.github/actions/db-migration@main
        with:
          namespace: ${{ inputs.namespace }}
          repository_name: ${{ inputs.repository_name }}
          pipeline_env: ${{ inputs.pipeline_env }}
          pipeline_tenant: ${{ inputs.pipeline_tenant }}
          pipeline_zone: ${{ inputs.pipeline_zone }}
      
      - name: Database migration with submodule
        if: ${{ env.SUBMODULE_GH_SECRET != '' }}
        uses: bitbuy-infrastructure/bb-cicd/.github/actions/db-migration@main
        with:
          namespace: ${{ inputs.namespace }}
          repository_name: ${{ inputs.repository_name }}
          pipeline_env: ${{ inputs.pipeline_env }}
          pipeline_tenant: ${{ inputs.pipeline_tenant }}
          pipeline_zone: ${{ inputs.pipeline_zone }}
          shared_folder: shared
