name: snyk-java-11

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  snyk-java-11:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
